# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nonverbal_communication_analysis/m6_Visualization/UI/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Visualizer(object):
    def setupUi(self, Visualizer):
        Visualizer.setObjectName("Visualizer")
        Visualizer.resize(1080, 640)
        self.centralwidget = QtWidgets.QWidget(Visualizer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr1_group_select = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr1_group_select.sizePolicy().hasHeightForWidth())
        self.fr1_group_select.setSizePolicy(sizePolicy)
        self.fr1_group_select.setObjectName("fr1_group_select")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fr1_group_select)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_confirm = QtWidgets.QPushButton(self.fr1_group_select)
        self.btn_confirm.setObjectName("btn_confirm")
        self.gridLayout.addWidget(self.btn_confirm, 0, 6, 1, 1)
        self.lbl_groupId = QtWidgets.QLabel(self.fr1_group_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_groupId.sizePolicy().hasHeightForWidth())
        self.lbl_groupId.setSizePolicy(sizePolicy)
        self.lbl_groupId.setObjectName("lbl_groupId")
        self.gridLayout.addWidget(self.lbl_groupId, 0, 0, 1, 1)
        self.cb_task = QtWidgets.QComboBox(self.fr1_group_select)
        self.cb_task.setEnabled(False)
        self.cb_task.setObjectName("cb_task")
        self.gridLayout.addWidget(self.cb_task, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.cb_groupId = QtWidgets.QComboBox(self.fr1_group_select)
        self.cb_groupId.setObjectName("cb_groupId")
        self.gridLayout.addWidget(self.cb_groupId, 0, 1, 1, 1)
        self.lbl_task = QtWidgets.QLabel(self.fr1_group_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_task.sizePolicy().hasHeightForWidth())
        self.lbl_task.setSizePolicy(sizePolicy)
        self.lbl_task.setObjectName("lbl_task")
        self.gridLayout.addWidget(self.lbl_task, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.fr1_group_select)
        self.fr2_video_player = QtWidgets.QFrame(self.centralwidget)
        self.fr2_video_player.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr2_video_player.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr2_video_player.setObjectName("fr2_video_player")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr2_video_player)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.fr2_video_player)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.fr2_video_player)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.fr2_video_player)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.fr2_video_player)
        self.fr3_overlays = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr3_overlays.sizePolicy().hasHeightForWidth())
        self.fr3_overlays.setSizePolicy(sizePolicy)
        self.fr3_overlays.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr3_overlays.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr3_overlays.setObjectName("fr3_overlays")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fr3_overlays)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fr1_subject = QtWidgets.QFrame(self.fr3_overlays)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr1_subject.sizePolicy().hasHeightForWidth())
        self.fr1_subject.setSizePolicy(sizePolicy)
        self.fr1_subject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr1_subject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr1_subject.setObjectName("fr1_subject")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fr1_subject)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.fr1_subject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.fr1_subject)
        self.fr2_group = QtWidgets.QFrame(self.fr3_overlays)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr2_group.sizePolicy().hasHeightForWidth())
        self.fr2_group.setSizePolicy(sizePolicy)
        self.fr2_group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr2_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr2_group.setObjectName("fr2_group")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.fr2_group)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.fr2_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_3.addWidget(self.checkBox_4, 1, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.fr2_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.fr2_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.fr2_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.horizontalLayout_5.addWidget(self.fr2_group)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.fr3_overlays)
        self.fr4_controls = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fr4_controls.sizePolicy().hasHeightForWidth())
        self.fr4_controls.setSizePolicy(sizePolicy)
        self.fr4_controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr4_controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr4_controls.setObjectName("fr4_controls")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fr4_controls)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btn_back = QtWidgets.QPushButton(self.fr4_controls)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_4.addWidget(self.btn_back)
        self.btn_play = QtWidgets.QPushButton(self.fr4_controls)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_4.addWidget(self.btn_play)
        self.btn_skip = QtWidgets.QPushButton(self.fr4_controls)
        self.btn_skip.setObjectName("btn_skip")
        self.horizontalLayout_4.addWidget(self.btn_skip)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.fr4_controls)
        Visualizer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Visualizer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 22))
        self.menubar.setObjectName("menubar")
        Visualizer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Visualizer)
        self.statusbar.setObjectName("statusbar")
        Visualizer.setStatusBar(self.statusbar)

        self.retranslateUi(Visualizer)
        QtCore.QMetaObject.connectSlotsByName(Visualizer)

    def retranslateUi(self, Visualizer):
        _translate = QtCore.QCoreApplication.translate
        Visualizer.setWindowTitle(_translate("Visualizer", "Visualizer"))
        self.fr1_group_select.setWindowTitle(_translate("Visualizer", "Frame"))
        self.btn_confirm.setText(_translate("Visualizer", "Confirm"))
        self.lbl_groupId.setText(_translate("Visualizer", "Group ID:"))
        self.lbl_task.setText(_translate("Visualizer", "Task:"))
        self.checkBox_2.setText(_translate("Visualizer", "CheckBox"))
        self.label.setText(_translate("Visualizer", "TextLabel"))
        self.label_2.setText(_translate("Visualizer", "TextLabel"))
        self.label_4.setText(_translate("Visualizer", "TextLabel"))
        self.label_3.setText(_translate("Visualizer", "TextLabel"))
        self.checkBox.setText(_translate("Visualizer", "CheckBox"))
        self.checkBox_4.setText(_translate("Visualizer", "CheckBox"))
        self.checkBox_3.setText(_translate("Visualizer", "CheckBox"))
        self.label_5.setText(_translate("Visualizer", "TextLabel"))
        self.label_6.setText(_translate("Visualizer", "TextLabel"))
        self.btn_back.setText(_translate("Visualizer", "«"))
        self.btn_play.setText(_translate("Visualizer", "Play"))
        self.btn_skip.setText(_translate("Visualizer", "»"))
