###
# YAML input parameter configuration file.
###

pose:
  keypoints: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 17, 18]
  averaging_method: "moving" # 'moving' or 'fixed' windows
face:
  averaging_method: "moving" # 'moving' or 'fixed' windows
